@url_dev = http://localhost:3000/v1/api
@api_key = 3eb5d56608d4645a0f521a9947ff3cc1fac7c6766f42734c1a53dd48501cbef52b46525a80f9abb8d774f8b7eae6e3c24c3c2f67ca72e5dd8cfa4a5d6de33aa0
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFiOTA2NTUzMGFkZjJjNzc5ZTViOTciLCJlbWFpbCI6InNob3A3QGV4YW1wbGUuY29tIiwiaWF0IjoxNzcyOTYxOTg0LCJleHAiOjE3NzMxMzQ3ODR9.t0nIZs-bKtjOU1t_LNGWIU2QArxbvIUOSyj3AEbONSI
@client_id = 69ab9065530adf2c779e5b97
@rtoken_id = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFiOTA2NTUzMGFkZjJjNzc5ZTViOTciLCJlbWFpbCI6InNob3A3QGV4YW1wbGUuY29tIiwiaWF0IjoxNzcyOTYxOTg0LCJleHAiOjE3NzM1NjY3ODR9.-q0nraJc9ArNaqwtOF0v-BvUWXI6eQBQMND4lyh81tE
# sudo lsof -i :3000
# sudo kill -9 <PID>

### 📦 Create Shop
### POST {{url_dev}}/shop/sign-up?lang=vi # can use this but i like header "Accept-Language: vi" instead
POST {{url_dev}}/shop/sign-up
Content-Type: application/json
x-api-key: {{api_key}}
Accept-Language: vi

{
  "name": "My Shop8",
  "email": "shop8@example.com",
  "password": "supersecure123",
  "phone": "0123456789",
  "address": "123 Main Street"
}

### 🔑 Login Shop
POST {{url_dev}}/login
Content-Type: application/json
x-api-key: {{api_key}}
Accept-Language: vi

{
  "email": "shop7@example.com",
  "password": "supersecure123"
}

### 📋 Get Draft Products (shop)
GET {{url_dev}}/product/drafts/all?limit=10&skip=0
x-api-key: {{api_key}}
authorization: {{access_token}}
x-client-id: {{client_id}}

### 🔄 Refresh Token
POST {{url_dev}}/shop/handlerRefreshToken
Content-Type: application/json
x-api-key: {{api_key}}
x-client-id: {{client_id}}
x-rtoken-id:{{rtoken_id}}




### Create Furniture Product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: {{api_key}}
x-client-id: {{client_id}}
authorization: {{access_token}}

{
  "product_name": "Furniture 01",
  "product_thumb": "https://example.com/nike-tshirt.jpg",
  "product_description": "Comfortable cotton T-shirt Furniture",
  "product_price": 25,
  "product_quantity": 100,
  "product_type": "Furniture",
  "product_attributes": {
    "brand": "Nike Furniture",
    "size": "L Furniture",
    "material": "Cotton Furniture"
  }
}

### Create Electronic Product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: {{api_key}}
x-client-id: {{client_id}}
authorization: {{access_token}}

{
  "product_name": "iPhone 15",
  "product_thumb": "https://example.com/iphone15.jpg",
  "product_description": "Latest Apple iPhone",
  "product_price": 999,
  "product_quantity": 50,
  "product_type": "Electronics",
  "product_attributes": {
    "manufacturer": "Apple",
    "model": "iPhone 15 Pro",
    "color": "Space Black"
  }
}

### Invalid Product Type
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: {{api_key}}
x-client-id: {{client_id}}
authorization: {{access_token}}

{
  "product_name": "Weird Product",
  "product_thumb": "https://example.com/weird.jpg",
  "product_price": 10,
  "product_quantity": 1,
  "product_type": "Food",
  "product_shop": "66cd81b2f5b4c23e44f8c1a2",
  "product_attributes": {}
}

### 🚪 Logout Shop
POST {{url_dev}}/logout
Content-Type: application/json
Accept-Language: vi
x-api-key: {{api_key}}
x-client-id: {{client_id}}
authorization: {{access_token}}




### Get Hello
GET http://localhost:3000/
x-api-key: {{api_key}}

### Create Item
POST http://localhost:3000/items
Content-Type: application/json

{
  "name": "Sample Item",
  "price": 99.99
}

### Get All Items
GET http://localhost:3000/items

### Get Item by ID
GET http://localhost:3000/items/1

### Update Item by ID
PUT http://localhost:3000/items/1
Content-Type: application/json

{
  "name": "Updated Item",
  "price": 150.0
}

### Delete Item by ID
DELETE http://localhost:3000/items/1
